### ISSUE TITLE
Network related metrics don't have container_name tag

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/heapster#1082]
Hello,

I'm running a dedicated heapster pod in a GKE (1.1) cluster with a dedicated influxdb sink:
```
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.0.0
        resources:
          limits:
            memory: 550Mi
        command:
          - /heapster
          - --source=kubernetes:''
          - --sink=influxdb:http://influxdb:8086
```

It seems that network related metrics don't have any container_name tag. All other metrics seems good.
Am'I missing something ? Is it intended ?

Regards,
