### ISSUE TITLE
Grafana + InfluxDB = Dashboard init failed

### ISSUE THREAD

**Issue by otaviosoares** [kubernetes/heapster#1185]
I'm running with the default manifests from https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb.
 
I'm able to login in Grafana but nothing works.

The request to http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/api/datasources/proxy/1/query?epoch=ms&q=SHOW+TAG+VALUES+FROM+%22uptime%22+WITH+KEY+%3D+%22nodename%22
returns an error: **Dashboard init failed
Template variables could not be initialized: InfluxDB Error: undefined**

VERSIONS:

InfluxDB: kubernetes/heapster_influxdb:v0.5
Heapster: kubernetes/heapster:canary
Grafana: gcr.io/google_containers/heapster_grafana:v2.6.0-2

LOGS:

Heapster: lots of
```
I0609 04:17:05.000219       1 manager.go:79] Scraping metrics start: 2016-06-09 04:16:00 +0000 UTC, end: 2016-06-09 04:17:00 +0000 UTC
I0609 04:17:05.590336       1 manager.go:152] ScrapeMetrics: time: 589.914318ms size: 274
I0609 04:18:05.000225       1 manager.go:79] Scraping metrics start: 2016-06-09 04:17:00 +0000 UTC, end: 2016-06-09 04:18:00 +0000 UTC
I0609 04:18:05.582961       1 manager.go:152] ScrapeMetrics: time: 582.497873ms size: 274
```

InfluxDB: lots of
```
[http] 2016/06/09 04:16:06 10.2.52.4 - root [09/Jun/2016:04:16:05 +0000] POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1 204 0 - heapster/1.1.0-beta2 e29dd6ca-2df8-11e6-8ebf-000000000000 993.49712ms
[wal] 2016/06/09 04:16:07 Flush due to idle. Flushing 24 series with 24 points and 1569 bytes from partition 1
[wal] 2016/06/09 04:16:07 write to index of partition 1 took 64.854312ms
[wal] 2016/06/09 04:16:12 Flush due to idle. Flushing 3082 series with 3082 points and 52394 bytes from partition 1
[wal] 2016/06/09 04:16:16 Flush due to idle. Flushing 24 series with 24 points and 1569 bytes from partition 1
[wal] 2016/06/09 04:16:20 write to index of partition 1 took 3.940463534s
[wal] 2016/06/09 04:16:21 write to index of partition 1 took 8.886478797s
[wal] 2016/06/09 04:16:26 Flush due to idle. Flushing 24 series with 24 points and 1569 bytes from partition 1
[wal] 2016/06/09 04:16:26 write to index of partition 1 took 29.23878ms
[wal] 2016/06/09 04:16:36 Flush due to idle. Flushing 24 series with 24 points and 1569 bytes from partition 1
[wal] 2016/06/09 04:16:36 write to index of partition 1 took 35.434233ms
[wal] 2016/06/09 04:16:47 Flush due to idle. Flushing 24 series with 24 points and 1569 bytes from partition 1
[wal] 2016/06/09 04:16:47 write to index of partition 1 took 61.260839ms
```

Grafana
```
2016/06/09 04:17:07 http: proxy error: dial tcp 10.3.188.80:8086: i/o timeout
2016/06/09 04:17:07 [I] Completed 127.0.0.1, 10.2.43.0 - "GET /query HTTP/1.1" 500 Internal Server Error 0 bytes in 30014822us
```

**Comment by boj** [comment]
I'm running the same versions listed above on a `kube-aws` built CoreOS cluster and just get an almost-big-blank nothing (a checkbox, and "{{alert.title}}").

I deleted the default heapster service and used the configs provided in this project instead to spin everything up.

**Comment by otaviosoares** [comment]
@boj Using the configs of this project did it work?

**Comment by boj** [comment]
@otaviosoares Unfortunately not, stuck at that mostly white screen.

**Comment by piosz** [comment]
Try to use Heapster in stable version and reopen if it fails.

**Comment by theobolo** [comment]
@piosz Hello guys ! I tried with the stable 1.1.0 and the 1.0.2 it's the same problem.

Object {data: "", status: 500, config: Object, statusText: "Internal Server Error"}

I tried with the DNS proxy name http://monitoring-influxdb:8086 and also with the Service IP but not working. For me it's not working since maybe 1 or 2 month.

I use Azkube to deploy Kubernetes like Otavio and we are on the Kubernetes 1.2.4 version :)

**Comment by boj** [comment]
There were some changes made to https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring/influxdb in the last few days, I was able to get everything working yesterday.

**Comment by piosz** [comment]
Thanks @boj for confirming!

@theobolo we are about to release Kubernetes 1.3 (should be available withing few days). Are you ok to wait until then?

cc @mwielgus

**Comment by theobolo** [comment]
@piosz Yes of course ! i'm waiting for that too (1.3 release) so it's alright. It's not an emergency case :P 

I'll try it soon as possible and give you my feedback. 

Thanks for your answers @boj @piosz

**Comment by piosz** [comment]
Looking forward for an update.

**Comment by djsly** [comment]
@titilambert does that ring a bell ? was this the reason why we had to upgrade to the latest InfluxDB ?

**Comment by piosz** [comment]
Haven't heard any update so closing the issue. @theobolo please re-open in case of problems.

**Comment by jonathan-kosgei** [comment]
I get the same error
**Template variables could not be initialized: InfluxDB Error: undefined**
To get it to work I had to comment out
`# kubernetes.io/cluster-service: 'true'`
in
```
apiVersion: v1
kind: Service
metadata:
  labels:
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    # kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  # type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    k8s-app: grafana
```

Is this repo supposed to be deployed exclusively as a cluster add-on?
