### ISSUE TITLE
Setup auth for grafana

### ISSUE THREAD

**Issue by agustincastanio** [kubernetes/heapster#1207]
I spent an afternoon trying to setup authentication for [Grafana](https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml).
GF_SECURITY_ADMIN_PASSWORD and GRAFANA_PASSWD should both be added to pod manifest with the same value.
I hope this helps someone and be documented somewhere (not sure where).

```
          env:
            # This variable is required to setup templates in Grafana.
            - name: INFLUXDB_SERVICE_URL
              value: http://monitoring-influxdb:8086
              # The following env variables are required to make Grafana accessible via
              # the kubernetes api-server proxy. On production clusters, we recommend
              # removing these env variables, setup auth for grafana, and expose the grafana
              # service using a LoadBalancer or a public IP.
            - name: GF_AUTH_BASIC_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: yourSecr3t
            - name: GRAFANA_PASSWD
              value: yourSecr3t
            - name: GF_SERVER_ROOT_URL
              value: https://grafana.tbxtest.com/
```
