### ISSUE TITLE
Unable to view Grafana 

### ISSUE THREAD

**Issue by owenmorgan** [kubernetes/heapster#1316]
From uncommenting the "type: LoadBalancer" from "grapfana-service.yaml" and running

$ kubectl create -f deploy/kube-config/influxdb/

Everything loads ok, and I'm able to see metrics on the Dashboard. But hitting the ELB thats created for Grafana, I see the below.

![image](https://cloud.githubusercontent.com/assets/10656664/18864970/c8142a88-8490-11e6-96bb-9b8464483b21.png)

access log on the pod shows.

> 2016-09-27T07:58:40.336230046Z 2016/09/27 07:58:40 [I] Completed 10.2.96.0 - "GET /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/app/app.ca0ab6f9.js HTTP/1.1" 404 Not Found 23 bytes in 403us

**Comment by aegixx** [comment]
Same issue here.

For the record, these configuration files are fairly out-of-date - though I'm not sure if that's the issue.

I'm hooking up Chronograf instead of Grafana, but I'll let you know if I have any success.

**Comment by LaurentDumont** [comment]
I was able to use the grafana service with a NodePort endpoint instead.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    targetPort: 3000
    nodePort: 30005
  selector:
    name: influxGrafana
```
