### ISSUE TITLE
influxdb error: missing tag value. labels empty?

### ISSUE THREAD

**Issue by jonaz** [kubernetes/heapster#1320]
Hi

Just installed heapster 1.1.0 in our development cluster and tried to send metrics to kubernetes. 

Influxdb is version 1.0.0. I have not tried older versions. 

This is the error i get:

```
'cpu/limit,host_id=192.168.3.57,hostname=192.168.3.57,labels=,namespace_id=24430b99-0de2-11e6-8afb-005056885071,namespace_name=kube-system,nodename=192.168.3.57,pod_id=8673b010-6dd8-11e6-bffc-005056880f6d,pod_name=kube-controller-manager-192.168.3.57,pod_namespace=kube-system,type=pod value=0 1475130540000000000': missing tag value"
```

According to https://github.com/influxdata/influxdb/issues/4421 this is expected behavior.
So metrics/sinks/influxdb/influxdb.go should not add the label if its empty. 

This is my heapster deployment:

```

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.1.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.1.0
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.1.0
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.1.0
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --sink=influxdb:http://dev-influx01.domain.com:8086?user=k8s&pw=asdf
        - image: gcr.io/google_containers/heapster:v1.1.0
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          command:
            - /eventer
            - --source=kubernetes:''
            - --sink=influxdb:http://dev-influx01.domain.com:8086?user=k8s&pw=asdf
        - image: gcr.io/google_containers/addon-resizer:1.3
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0.5m
            - --memory=140Mi
            - --extra-memory=4Mi
            - --threshold=5
            - --deployment=heapster-v1.1.0
            - --container=heapster
            - --poll-period=300000
            - --estimator=exponential
        - image: gcr.io/google_containers/addon-resizer:1.3
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=200Mi
            - --extra-memory=500Ki
            - --threshold=5
            - --deployment=heapster-v1.1.0
            - --container=eventer
            - --poll-period=300000
            - --estimator=exponential

```
