### ISSUE TITLE
Love/hate relationship with setup_grafana.go in the sample image

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes/heapster#1491]
The sample [heapster-influxdb-grafana](https://github.com/kubernetes/heapster/commits/master/deploy/kube-config/influxdb
) deployment, images and [description](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md) are great. Many thanks to the authors.

I hit a couple of snags with the [`setup_grafana.go`](https://github.com/kubernetes/heapster/blob/master/grafana/setup_grafana.go) bootstrap tool and the grafana container v4.0.2 I wanted to share. 

(1) If you configure the Grafana admin user to not be the default admin/admin then `setup_grafana.go` stops working.
```
        - name: GF_SECURITY_ADMIN_USER
          value: myadmin
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: GF_SECURITY_ADMIN_PASSWORD
```
This is because `setup_grafana.go` uses it own separate environment variables for the bootstrap admin user. You can work around it by setting those too.
```
        - name: GRAFANA_USER
          value: myadmin
        - name: GRAFANA_PASSWD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: GF_SECURITY_ADMIN_PASSWORD
```
I'd propose that `setup_grafana.go` use the same named environment variables as grafana.

(2) The `setup_grafana.go` API check doesn't notice it gets 401 responses from the API and acts in the logs like the init worked, when it hasn't.
```
t=2017-01-27T21:35:02+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=
t=2017-01-27T21:35:07+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/org status=401 remote_addr=[::1] time_ms=99ns size=42
Connected to the Grafana dashboard.
t=2017-01-27T21:35:07+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/datasources status=401 remote_addr=[::1] time_ms=101ns size=42
The datasource for the Grafana dashboard is now set.
```

(3) When `setup_grafana.go` runs successfully, for me it is misconfigures the data source URL for InfluxdDB. If my InfluxDB service name is 'influxdb` and the environment variable is as follows.
```
        - name: INFLUXDB_HOST
          value: influxdb
```
The after `setup_grafana.go` the configured data source URL in the UI looks like below and doesn't work.
```
http://influxdb:tcp://10.3.0.98:8086
```
If I edit that to `http://influxdb:8086` the data source starts working fine. Not sure what happens there.

(4) The container has no root certificate collection, and so configurations like InfluxDB and SMTP have to forgo certificate checks, and CloudWatch and Slack won't work at all. I guess the answer is to build the container myself or map the root certificates collection from a PV. But it seems to me like a reasonable addition to the base container?

Tested with
```
gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
```

(5) As widely documented is multiple other issues, you currently need to add explicit architecture suffixes to the image names that are in the heapster/influxdb/grafana sample YAML files.
