### ISSUE TITLE
Support for Kubelet authentication/authorization

### ISSUE THREAD

**Issue by normanrz** [kubernetes/heapster#1498]
Currently, heapster only works with `kubelet`'s read-only port (default: 10255). 
It would be great if it could use `kubelet`'s standard https port and authenticate with a client certificate. 
To communicate with kubelets, the api server has `--kubelet-client-certificate` and `--kubelet-client-key` arguments.
See [kubelet documentation](https://kubernetes.io/docs/admin/kubelet-authentication-authorization/).

**Comment by DirectXMan12** [comment]
We should already do this if you enable the `kubeletHttps` option in the source config.  We appear to try to connect with the same client certificates that we use to connect to Kubernetes.

**Comment by qianzhangxa** [comment]
> We appear to try to connect with the same client certificates that we use to connect to Kubernetes.

@DirectXMan12 Do you mean Heapster (assume it is running as a pod in Kubernetes cluster) will use the token in the default service account to connect to kubelet? If so, I think kubelet should be started with the flag `--client-ca-file`, and its value should be same with the flag `--client-ca-file` of kube-apiserver, right? And if kubelet is started in this way, will the communication from kube-apiserver to kubelet be affected? E.g., when I run "kubectl logs ..." to get logs of a pod, kube-apiserver needs to connect to kubelet to get the logs, will this function still work?

**Comment by jejer** [comment]
Seems we can't config cert and key for kubelet connection.
I have tried to set --tls-cert-file / --tls-cert / --authorization-kubeconfig , all report "Unauthorized".
Heapster version v1.5.0

**Comment by SpComb** [comment]
If the kubelet is configured with `--authorization-mode=Webhook --client-ca-file=...` (the case for `kubeadm`), then the kubelet API does not seem to accept a bearer token for authentication, but instead expects a TLS client cert signed by the kube CA: https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication

A configuration like `--source=kubernetes:?kubeletHttps=true&kubeletPort=10250` will use the in-cluster-config with the serviceaccount bearer token and the kube CA. This will first fail because the kubelet uses a self-signed cert for its bare hostname:

```
E0320 10:59:05.041917       1 manager.go:101] Error in scraping containers from kubelet_summary:167.99.136.175:10250: Get https://...:10250/stats/summary/: x509: cannot validate certificate for ... because it doesn't contain any IP SANs
```

With `?insecure=true`, this will fail because the kubelet expects a TLS client cert, and does not look at the serviceaccount bearer token:

```
E0320 11:35:05.036030       1 manager.go:101] Error in scraping containers from kubelet_summary:...:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=stats)"
```

It seems to be possible to get this to work, but this requires provisioning heapster with a custom kubeconfig + client cert signed by the kube CA, containing a subject user bound to the heapster role.  The heapster configuration for that would then look something like `--source=kubernetes.summary_api:https://kubernetes.default.svc?inClusterConfig=false&kubeletHttps=true&kubeletPort=10250&auth=.../heapster.conf`. 

The kubeconfig needs to have a `users[*].user.client-certificate` with a subject user/group bound to the heapster role for both kube and kubelet API access. The kubeconfig will presumably also need `insecure-skip-tls-verify: true` to talk to the kubelet API (unless using `--feature-gates=RotateKubeletServerCertificate=true` to provision the kubelet with a server cert signed by the kube CA?), which unfortunately also disables cert verification for the kube API.

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://10.96.0.1
    insecure-skip-tls-verify: true
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: default-auth
  user:
    client-certificate: ../heapster-client.crt
    client-key: .../heapster-client.key
```
