### ISSUE TITLE
"x509: failed to load system roots and no roots provided" when using grafana slack alerts

### ISSUE THREAD

**Issue by Shimi** [kubernetes/heapster#1611]
maybe root CA certificates are missing from the docker image?

**Comment by munnerz** [comment]
They most likely are missing from the Docker image, which I (personally) see as best practice, as root CAs might be revoked or updated, meaning your image will eventually become incompatible with newer certs (or, conversely, a certificate that should no longer be trusted may be trusted)

I think best practice here is to pass through `/etc/ssl/certs` from your host machine. Alternatively, an init container with a shared emptyDir at `/etc/ssl/certs` can be used to populate the directory.

**Comment by Shimi** [comment]
Thanks @munnerz, I used volumeMount

**Comment by NullVoxPopuli** [comment]
I tried this, and it didn't work (error persists)

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        - mountPath: /etc/ssl/certs
          name: ca-certificates
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GRAFANA_PORT
          value: "3000"
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: ca-certificates
        emptyDir: {}
      - name: grafana-config
        configMap:
          name: grafana-config-ini
          items:
            - key: grafana.config.ini
              path: grafana.ini

---
apiVersion: v1
kind: Service
metadata:
  labels:
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  # type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    k8s-app: grafana

```

**Comment by NullVoxPopuli** [comment]
I had to change my volumes def from emptyDir to

```yaml
      - name: ca-certificates
        hostPath:
          path: /etc/ssl/certs
```
