### ISSUE TITLE
Use Grafana Env Variables for Dashboard Setup

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/heapster#1623]
Grafana setup/bootstrapper doesn't use the same environment variables used for Grafana configuration.

Scenario:
In `grafana.yaml`, edit to use the following environment variables (assuming appropriate `grafana-secrets` object exists in cluster).
```
env:
- name: GF_SECURITY_ADMIN_USER
  valueFrom:
    secretKeyRef:
      name: grafana-secrets
      key: security-admin-user
- name: GF_SECURITY_ADMIN_PASSWORD
  valueFrom:
    secretKeyRef:
      name: grafana-secrets
      key: security-admin-password
```

Expected behavior:

1. Setup program uses Grafana admin username/password from environment variable
2. Kubernetes cluster dashboards load up in Grafana.

Actual behavior:

1. Setup program fails to authenticate with Grafana
2. Dashboards don't load.
