### ISSUE TITLE
Missing CA Root Certificates in Grafana Image

### ISSUE THREAD

**Issue by wedgeV** [kubernetes/heapster#1653]
Slack notifications use HTTPS and are broken due to the missing CA roots in the grafana image.

**Comment by DirectXMan12** [comment]
can you just inject the CA roots via a volume (hostpath or otherwise)?

**Comment by espala** [comment]
Hello, I have same problem.. How can I do this?

**Comment by DirectXMan12** [comment]
https://kubernetes.io/docs/concepts/storage/volumes/#hostpath provides instructions for how to use volumes (specifically, hostpath volumes).  You could also place them in a secret, and mount them in that way.

**Comment by espala** [comment]
Hello,

I try, but it does not succeed. Can you help me ?

my grafana.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        - mountPath: /etc/ssl/certs
          name: ca-certificates
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: ca-certificates
        hostPath:
          path: /etc/ssl/certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30078
  selector:
    k8s-app: grafana

```
logs;

```
t=2017-06-01T19:57:40+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 4 v3"
t=2017-06-01T19:57:40+0000 lvl=info msg="Created default admin user: [admin]"
t=2017-06-01T19:57:40+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-06-01T19:57:40+0000 lvl=warn msg="Plugin dir does not exist" logger=plugins dir=/usr/share/grafana/data/plugins
t=2017-06-01T19:57:40+0000 lvl=info msg="Plugin dir created" logger=plugins dir=/usr/share/grafana/data/plugins
t=2017-06-01T19:57:40+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-06-01T19:57:40+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-06-01T19:57:40+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=
Connected to the Grafana dashboard.
The datasource for the Grafana dashboard is now set.


t=2017-06-01T19:58:02+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=0 isDefault=false
t=2017-06-01T19:58:02+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=0 notification=test
t=2017-06-01T19:58:02+0000 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="Post https://hooks.slack.com/services/XXXXXXX/kslmdfDSFKLsdfFKDLSKNM: x509: failed to load system roots and no roots provided" webhook=test

t=2017-06-01T20:08:24+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=0 isDefault=false
t=2017-06-01T20:08:24+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=0 notification=test
t=2017-06-01T20:08:24+0000 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="Post https://hooks.slack.com/services/XXXXXXX/kslmdfDSFKLsdfFKDLSKNM: x509: failed to load system roots and no roots provided" webhook=test

```

pod details;

```
/etc/ssl/certs # hostname
monitoring-grafana-1063424755-7qtjn

/etc/ssl/certs # pwd
/etc/ssl/certs

/etc/ssl/certs # ls -lah
total 624
drwxr-xr-x    2 root     root        4.0K Jun  1 20:07 .
drwxr-xr-x    3 root     root        4.0K Jun  1 19:57 ..
-rw-r--r--    1 root     root        2.3K Jun  1 20:07 Makefile
-rwxrwxrwx    1 root     root      258.0K Jun  1 20:03 ca-bundle.crt
-rwxrwxrwx    1 root     root      340.7K Jun  1 20:06 ca-bundle.trust.crt
-rwxr-xr-x    1 root     root         611 Jun  1 20:06 make-dummy-cert
-rwxr-xr-x    1 root     root         830 Jun  1 20:07 renew-dummy-cert

/etc/ssl/certs # stat -c '%A %a %n' *
-rw-r--r-- 644 Makefile
-rwxrwxrwx 777 ca-bundle.crt
-rwxrwxrwx 777 ca-bundle.trust.crt
-rwxr-xr-x 755 make-dummy-cert
-rwxr-xr-x 755 renew-dummy-cert

```

**Comment by DirectXMan12** [comment]
Here's the list of where go looks for root certs: https://github.com/golang/go/blob/master/src/crypto/x509/root_linux.go#L9

Looks like your setup doesn't quite match what it's expecting -- you've mixed an matched paths and file names from a couple different distros, AFAICT.

**Comment by espala** [comment]
Yes, finally i'm succeeded. I missed the detail, thank you for your support.

my temporary grafana.yaml;

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        - mountPath: /etc/ssl
          name: ssl-folder
        - mountPath: /etc/pki
          name: pki-folder
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: ssl-folder
        hostPath:
          path: /etc/ssl
      - name: pki-folder
        hostPath:
          path: /etc/pki

---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30078
  selector:
    k8s-app: grafana

```
