### ISSUE TITLE
heapster-grafana-amd64:v4.2.0 is not found 

### ISSUE THREAD

**Issue by datamaker** [kubernetes/heapster#1669]
hello,

I want to grafana install in my kubernetes
There is v4.0.2 but not v4.2.0.

**heapster/deploy/kube-config/influxdb/grafana.yaml**
```
    spec:
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.2.0
        ports:
        - containerPort: 3000
          protocol: TCP
```

```
datamaker-MacBook-Pro:~ macbookpro$ docker pull gcr.io/google_containers/heapster-grafana-amd64:v4.2.0
Pulling repository gcr.io/google_containers/heapster-grafana-amd64
Tag v4.2.0 not found in repository gcr.io/google_containers/heapster-grafana-amd64
datamaker-MacBook-Pro:~ macbookpro$ docker pull gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
v4.0.2: Pulling from google_containers/heapster-grafana-amd64
4b0bc1c4050b: Pull complete 
25cb5da25c3b: Pull complete 
d1882af57e94: Pull complete 
734595366ce3: Pull complete 
f945929e77af: Pull complete 
Digest: sha256:ab7927a702b41e4ffaf1e54fc9647db32a71ea971f441e75906ee83daa3c898d
Status: Downloaded newer image for gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
```

and,
my terminal says - **grafana-cli command not found.**
How do I run grafana-cli  plugins install in kubernetes?

```
$ kubectl exec -it grafana-ert4wr -- /bin/sh
$ grafana-cli plugins install grafana-worldmap-panel
 grafana-cli command not found.
```
