### ISSUE TITLE
Template variables could not be initialized: InfluxDB Error: undefined

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/heapster#1679]
I get the error
**Template variables could not be initialized: InfluxDB Error: undefined**
After deploying the setup with `kubectl apply -f heapster/deploy/kube-config/influxdb/`
To get it to work I had to comment out
`# kubernetes.io/cluster-service: 'true'`
in
```
apiVersion: v1
kind: Service
metadata:
  labels:
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    # kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  # type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    k8s-app: grafana
```

Is this repo supposed to be deployed exclusively as a cluster add-on?
