### ISSUE TITLE
Adding Health Check to Influxdb Kubernetes container

### ISSUE THREAD

**Issue by anarwal27** [kubernetes/heapster#1760]
I am deploying influxdb in kubernetes using the yaml and wanted to add health-check for Influxdb's. Currently to perform health check, I curl an endpoint, `curl -sl -I -k https://hostname:port/ping` I wanted to leverage this and add to livenessProbe in kube yaml, following kuberenetes documentation (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) I have added the following:

```
livenessProbe:
            httpGet:
              path: "/ping"
              port: 8086
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - containerPort: 8086
```
However health-check fails and when I describe the pod, it shows some weird URL:

```
Liveness:http-get http://:8086/hostname/ping delay=15s timeout=5s period=10s #success=1 #failure=3
```
Note: I curl on https whereas when performing health-check, as it is from inside the cluster I am using http. Also port exposed for external use is different, that is what I have used in curl command (it is 30086) whereas for health check I have used internal port 8086
