### ISSUE TITLE
The default value of option "--requestheader-group-headers" does not work

### ISSUE THREAD

**Issue by wjiangjay** [kubernetes/heapster#1766]
Reproduced version:
both v1.3.0 & 1.4.0

Reproduced steps:
1. Setup heapster without --requestheader-group-headers option
```yaml
    spec:
      containers:
      - command:
        - /heapster
        - --api-server
        - --bind-address=0.0.0.0
        - --secure-port=8443
        - --requestheader-client-ca-file=/var/run/kubernetes/request-header-ca.crt
        - --tls-ca-file=/var/run/kubernetes/client-ca.crt
        - --source=kubernetes:https://kubernetes.default.svc?kubeletPort=10250&kubeletHttps=true
        - --sink=influxdb:http://monitoring-influxdb.wjiang.svc:8086

```
2. try to access the heapster api with the default requestheader group headers
```
# curl -k --cert /etc/origin/master/master.proxy-client.crt --key /etc/origin/master/master.proxy-client.key -H "X-Remote-User: wjiang" -H "X-Remote-Group: balabala" https://172.30.234.103/apis/metrics/v1alpha1/nodes
User "wjiang" cannot list nodes.metrics at the cluster scope.: "User \"wjiang\" cannot list all nodes.metrics in the cluster"
# curl -k --cert /etc/origin/master/master.proxy-client.crt --key /etc/origin/master/master.proxy-client.key -H "X-Remote-User: wjiang" -H "x-remote-group: balabala" https://172.30.234.103/apis/metrics/v1alpha1/nodes
User "wjiang" cannot list nodes.metrics at the cluster scope.: "User \"wjiang\" cannot list all nodes.metrics in the cluster"
```
3. Check the heapster log to make sure requestheader group header work
```
  | I0811 09:35:01.594159       1 request.go:991] Request Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"verb":"list","group":"metrics","version":"v1alpha1","resource":"nodes"},"user":"wjiang",**"group":["system:authenticated"]}**,"status":{"allowed":false}}
  | I0811 09:35:01.594217       1 round_trippers.go:395] POST https://172.30.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews
  | I0811 09:35:01.594243       1 round_trippers.go:402] Request Headers:
  | I0811 09:35:01.594249       1 round_trippers.go:405]     User-Agent: heapster/v0.0.0 (linux/amd64) kubernetes/$Format
  | I0811 09:35:01.594255       1 round_trippers.go:405]     Accept: application/json, */*
  | I0811 09:35:01.594260       1 round_trippers.go:405]     Content-Type: application/json
  | I0811 09:35:01.594264       1 round_trippers.go:405]     Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ3amlhbmciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaGVhcHN0ZXItdG9rZW4tMjVkcnMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaGVhcHN0ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI2OTMzNWM2ZS03ZTQyLTExZTctOWFlMS0wZWRiODdjYTk0ZjgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6d2ppYW5nOmhlYXBzdGVyIn0.dS2DDm2hrlj32Vlmouw2ATJPn3taZP25SRTjPszwH3xLNplZWlxa4MFbKtFUgX-pyH7cOGffh_P79r1TYi7aCINytwpOmUkW3TsfgeAbS1Dk7pxEtQDISWHLOoUVojTdYP0RAiNE-1KqFk1dk_b18b8YZQns8ChE6t87fV1RkmPlJpi83cd3t287JIjUf7yPDJ7TVP8wQapHyGK8GRYvprEJ8WZllBVKPkc3db7BPILjRkJsfpgPwJ4a-TuM0bbbdNYOiI7HFdDug9dNT9BovU4haqbJB8jcQoUsRFr4LPq_OdUUVNeSV_uBEZLX0d7wytVPzqnG_jCHoZxyAzS3Ug
  | I0811 09:35:01.638748       1 round_trippers.go:420] Response Status: 201 Created in 44 milliseconds
  | I0811 09:35:01.638772       1 round_trippers.go:423] Response Headers:
  | I0811 09:35:01.638778       1 round_trippers.go:426]     Content-Type: application/json
  | I0811 09:35:01.638782       1 round_trippers.go:426]     Content-Length: 365
  | I0811 09:35:01.638786       1 round_trippers.go:426]     Date: Fri, 11 Aug 2017 09:35:01 GMT
  | I0811 09:35:01.638790       1 round_trippers.go:426]     Cache-Control: no-store
  | I0811 09:35:01.638818       1 request.go:991] Response Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"verb":"list","group":"metrics","version":"v1alpha1","resource":"nodes"},"user":"wjiang","group":["system:authenticated"]},"status":{"allowed":false,"reason":"User \"wjiang\" cannot list all nodes.metrics in the cluster"}}

```
