### ISSUE TITLE
Cant access grafana UI

### ISSUE THREAD

**Issue by felixPG** [kubernetes/heapster#1831]
Hi, just testing heapster with grafana following this guide: https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md

All deployed OK, all running but I cant access to the grafana UI. I cant use nodePort or loadbalancer, I have ingress option or externalIPs but using whatever of this two options  I cant access the dashboard:

Ingress config is simple:
``` 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
       paths:
       - path:
         backend:
          serviceName: monitoring-grafana
          servicePort: 5432
``` 
5432 is the port that I have in the grafana service mapped to the internal grafana port 3000.

Please, How I can solve this?
