### ISSUE TITLE
No metrics for pod 

### ISSUE THREAD

**Issue by ori-stoliar** [kubernetes/heapster#1859]
kubernetes version: v1.7.4
heapster version: 1.4.0

I applied horizontal autoscale configuration on one of my pods and using HPA to get info about the status of it:
```
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu on container thumbor in pod dev/dev-thumbor-4162317122-70rgf
```
The deployment of my pod looks like:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thumbor
  namespace: dev
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: thumbor
    spec:
      containers:
      - image: xxx/thumbor
        name: thumbor
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
```
The heapster logs indicate that there are no matrics for the specified pod:
`I1026 11:04:13.700779       1 handlers.go:215] No metrics for pod dev/dev-thumbor-4162317122-70rgf`

My heapster deployment configuration consists of this parameters:
```
        - --source=kubernetes.summary_api:https://kubernetes.default.svc
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
        - --metric-resolution=20s
```
I went through the following [issue](https://github.com/kubernetes/heapster/issues/1470) but no luck using it.

**Comment by DirectXMan12** [comment]
Your issue is listed in the pod status conditions that you pasted in 

> the HPA was unable to compute the replica count: missing request for cpu on container thumbor in pod dev/dev-thumbor-4162317122-70rgf

You'll need to set a request for CPU in your pod spec for that container, like

```yaml
containers:
- image: xxx/thumbor
  ...
  resources:
    requests:
      cpu: 500m
```

That should fix your issue.
