### ISSUE TITLE
system:heapster ClusterRole lacking nodes/stats get privileges

### ISSUE THREAD

**Issue by r0bj** [kubernetes/heapster#1936]
The `system:heapster` ClusterRole appears to be missing the ability to GET to `nodes/stats` resource.

heapster deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
        version: v6
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.5.0
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes.summary_api:https://kubernetes.default.svc?kubeletHttps=true&kubeletPort=10250&insecure=true
        - --sink=influxdb:http://dev.os-metrics-db.service.poz-dev.consul:8086?withfields=true&db=k8s
        - --metric-resolution=30s
```

error messages from API server:
```
I0123 12:28:05.087431       1 rbac.go:116] RBAC DENY: user "system:serviceaccount:kube-system:heapster" groups ["system:serviceaccounts" "system:serviceaccounts:kube-system" "system:authenticated"] cannot "get" resource "nodes/stats" named "dev-k8s-lb-p1" cluster-wide
```

error message from heapster:
```
E0123 12:28:35.033599       1 manager.go:101] Error in scraping containers from kubelet_summary:10.14.30.116:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:heapster, verb=get, resource=nodes, subresource=stats)"
```

Issue is fixed after adding those lines to ClusterRole `system:heapster`:
```
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
```

kubernetes: 1.9.1
heapster: 1.5.0

**Comment by OrlinVasilev** [comment]
@r0bj - have started the kubelet with authorization-webhook true ? currently I'm facing the same issue which I cannot solve

**Comment by r0bj** [comment]
As a workaround I just created separate ClusterRole and use it for heapster:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: heapster-custom-fix
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
```
