### ISSUE TITLE
Error CrashLoopBackOff in heaspter container with statsd sink configuration

### ISSUE THREAD

**Issue by bangau1** [kubernetes/heapster#1969]
**Description**

Hi,

I got error when trying to deploy the Heapster with statsd sink configuration. The error is segmentation fault.

**Steps to reproduce:**
- kubectl apply -f heapster-rbac.yaml
```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
```
- kubectl apply -f heapster.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: k8s.gcr.io/heapster-amd64:v1.5.1
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink="statsd:udp://dd-agent-service.default:8125"
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
          readOnly: true
        env:
          - name: DATADOG_AGENT_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster

```

Note: `dd-agent-service.default` is a kubernetes service hostname to abstract the dd-agent daemonset pod running in all our nodes.

**Describe the results you received:**
The result is the heapster pod is in CrashLoopBackOff state. Specifically, I got this error message inside the heapster container:
```
Container	Timestamp	Message
heapster 	Mar 2, 2018, 11:03:20 AM	/go/src/k8s.io/heapster/metrics/heapster.go:89 +0x458
heapster 	Mar 2, 2018, 11:03:20 AM	main.main()
heapster 	Mar 2, 2018, 11:03:20 AM	/go/src/k8s.io/heapster/metrics/heapster.go:194 +0x8d
heapster 	Mar 2, 2018, 11:03:20 AM	main.createAndInitSinksOrDie(0xc42028f3b0, 0x1, 0x1, 0x0, 0x0, 0x4a817c800, 0x0, 0x0, 0xc420154740, 0x0, ...)
heapster 	Mar 2, 2018, 11:03:20 AM	/go/src/k8s.io/heapster/metrics/sinks/factory.go:90 +0x563
heapster 	Mar 2, 2018, 11:03:20 AM	k8s.io/heapster/metrics/sinks.(*SinkFactory).BuildAll(0xc4205e1cd8, 0xc42028f3b0, 0x1, 0x1, 0x0, 0x0, 0x7fb87afb8400, 0x0, 0x0, 0x0, ...)
heapster 	Mar 2, 2018, 11:03:20 AM	goroutine 1 [running]:
heapster 	Mar 2, 2018, 11:03:20 AM	
heapster 	Mar 2, 2018, 11:03:20 AM	[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x15f77a3]
heapster 	Mar 2, 2018, 11:03:20 AM	panic: runtime error: invalid memory address or nil pointer dereference
heapster 	Mar 2, 2018, 11:03:20 AM	I0302 04:03:20.258025 1 configs.go:62] Using kubelet port 10255
heapster 	Mar 2, 2018, 11:03:20 AM	I0302 04:03:20.258013 1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version v1
heapster 	Mar 2, 2018, 11:03:20 AM	I0302 04:03:20.257857 1 heapster.go:79] Heapster version v1.5.1
heapster 	Mar 2, 2018, 11:03:20 AM	I0302 04:03:20.257820 1 heapster.go:78] /heapster --source=kubernetes:https://kubernetes.default --sink="statsd:udp://dd-agent-service.default:8125"
```

**Describe the results you expected:**
I expect that at least the heapster pod is running fine and I can check whether the heapster metrics is getting pushed to datadog statsd server (dd-agent)

**Output of `heapster --version`:**
Unfortunately the heapster container is in `Pod errors: CrashLoopBackOff ` state. So I can't check the heapster version. However, in heapster.yaml, I set the container image to `k8s.gcr.io/heapster-amd64:v1.5.1` image, so it should be v1.5.1.

![screenshot from 2018-03-02 13-33-10](https://user-images.githubusercontent.com/352737/36886297-45aa5e2c-1e1e-11e8-9837-ac1d3e455894.png)

**Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}

```

Please advice,
Best,
Agung
