### ISSUE TITLE
I create it and got an error while docker startup

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes/heapster#2047]
**Description**
`run: open server: listen: listen tcp 207.226.143.108:8088: bind: cannot assign requested address`

How dit i do ?

**Comment by DirectXMan12** [comment]
Please provide more information about your setup, including your Kubernetes pod manifest.

**Comment by TracyBin** [comment]
I face the same issue

**Comment by TracyBin** [comment]
kubernetes 1.10.7 
influxdb.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: k8s.gcr.io/heapster-influxdb-amd64:v1.5.2
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxdb

```
