### ISSUE TITLE
influxdb error: Mapping Values not Allowed in This Context

### ISSUE THREAD

**Issue by ILMostro** [kubernetes/heapster#2094]
This might be somewhat similar to [Issue 1738](https://github.com/kubernetes/heapster/issues/1738), but that's closed; and, as far as I can tell, it's different enough to warrant opening this new issue.

There's a failure to create grafana, influxdb, heapster when executing the following:

```
$ kubectl create -f deploy/kube-config/influxdb
deployment.extensions/monitoring-grafana created
service/monitoring-grafana created
serviceaccount/heapster created
deployment.extensions/heapster created
service/heapster created
deployment.extensions/monitoring-influxdb created
error: error parsing deploy/kube-config/influxdb/influxdb.yaml: error converting YAML to JSON: yaml: line 13: mapping values are not allowed in this context
```

This is on a debian server (master)
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:08:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

The file in question reads as follows:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: k8s.gcr.io/heapster-influxdb-amd64:v1.5.2
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  type: NodePort
    ports:
    - port: 8086
      targetPort: 8086
  selector:
    k8s-app: influxdb
```

Line 13 refers to the nested `spec` section, AFAICT.
