### ISSUE TITLE
Grafana UI credentials failing 

### ISSUE THREAD

**Issue by Naresht-vedams** [kubernetes/heapster#526]
http://172.16.2.92:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana

When we browse through the above URL it is asking login credentials as I provided username and password from ~/.kube/config,no response when we try to login 

**cat ~/.kube/config**

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://172.16.2.92:8080
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: bmm4uNESv2rOAOYy
    username: admin
```
Does anyone else encounter the same problem? Any help or suggestions will be appreciated, thanks.
