### ISSUE TITLE
Retry connection attempt to hawkular

### ISSUE THREAD

**Issue by z0rc** [kubernetes/heapster#651]
I'm trying to test heapster with hawkular with docker-compose.
```
heapster:
    image: kubernetes/heapster:canary
    ports:
        - "8082:8082"
    links:
        - hawkular
        - cadvisor
    command: --source="cadvisor:external?cadvisorPort=8081" --sink=hawkular:http://hawkular/?user=jdoe&pass=password --vmodule=*=4
    volumes:
        - ./sample-hosts.json:/var/run/heapster/hosts
cadvisor:
    image: google/cadvisor:latest
    ports:
        - "8081:8080"
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
hawkular:
    image: hawkular/hawkular:latest
    ports:
        - "80:8080"
    links:
        - cassandra
    environment:
        CASSANDRA_NODES: cassandra
        TEST_MODE: true
cassandra:
    image: cassandra:2.1
```
The problem is hawkular takes some time to come up, but heapster doesn't wait and just dies:
```
F1014 16:04:52.539332       1 heapster.go:67] Get http://hawkular///metrics?type=gauge: dial tcp 172.17.0.67:80: connection refused
```
Would it be possible to implement connection retry policy?
