### ISSUE TITLE
Persist Grafana and InfluxDB

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/heapster#768]
Hi,

I am new to the Heapster, InfluxDB and Grafana combi. I installed it on a dedicated cluster node together in one POD. I have noticed that when the POD restarts, for example when the node reboots, all data is gone. 

I would like to make the data in Grafana (mainly my crafted graphs) and also the InfluxDB persistent. What would be the recommended way to achieve this?

Many thanks

**Comment by andrejvanderzee** [comment]
I have tried with volumes hostDir like this but it does not create anything in the host's path:

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
  name: influxdb-grafana
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      nodeSelector:
        role: monitor
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:http://172.31.7.28:8080
        - --sink=influxdb:http://127.0.0.1:8086
      - name: grafana
        image: kubernetes/heapster_grafana:v2.1.0
        ports: 
        - containerPort: 3000
          hostPort: 3000
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://127.0.0.1:8086
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        source:
          hostDir:
            path: /var/lib/monitor/influxdb
      - name: grafana-storage
        source:
          hostDir:
            path: /var/lib/monitor/grafana

**Comment by vishh** [comment]
cc @piosz

**Comment by piosz** [comment]
cc @mwielgus

**Comment by paulbakker** [comment]
Any news on this issue? I tried this with an EBS volume. When I delete the pod and attach the EBS to another container, I see it still contains the `log/grafana` and `lib/grafana` folders, but they are both empty.

**Comment by hlamer** [comment]
This is a bug in the `influxdb-grafana-controller.yaml`. It tries to mount volume to `/var`, but grafana dockerfile overwrites this by mounting volume to `/var/lib/grafana`.

Next peace of yaml works for me:

`influxdb-grafana-controller.yaml`:
```
...
          volumeMounts:
          - name: grafana-persistent-storage
            mountPath: /var/lib/grafana
      volumes:
      - name: influxdb-persistent-storage
        emptyDir: {}
      - name: grafana-persistent-storage
        hostPath:
          path: /var/lib/grafana
```
Note that grafana dashboards are preserved, but not data in influxdb
