### ISSUE TITLE
Heapster 18 and influxdb 10 get 404 at create db

### ISSUE THREAD

**Issue by git001** [kubernetes/heapster#977]
Hi.

today we try to setup the following.

Openshift v3.1.1.6
kubernetes v1.1.0-origin-1107-g4c8e6f4
kubernetes/heapster:v0.18.3
InfluxDB starting, version 0.10.0, branch 0.10.0, commit b8bb32ecad9808ef00219e7d2469514890a0987a, built 2016-02-04T17:06:04.850564

After successfully creating the pods we always get the following errors and no database.

`
E0216 08:46:08.341101       1 driver.go:326] Database creation failed: Server returned (404): 404 page not found
`

When we switch to "Heapster version 0.19.1" we are able to create the database but this version is not able to read data from kubernetes/openshift.

Attached the ReplicationController setup.

What we are able to use is the 'Influx Server 0.8.8' with kubernetes/heapster:v0.18.3.
Are there any plans that heapster is able to read kubernetes/openshift again?

```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    cw: monitoring
    app: heapster-controller
    version: v6
  name: monitoring-heapster
spec:
  replicas: 1
  selector:
    version: v6
  template:
    metadata:
      labels:
        cw: monitoring
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:v0.18.3
        imagePullPolicy: Always
        command:
        - /heapster
        - -source=kubernetes:https://kubernetes.default?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
        - -sink=influxdb:http://influxdb:8086
        - -logtostderr=true
        - -alsologtostderr
        - -allowed_users=system:serviceaccount:cw-metrics:heapster
        - -tls_cert=/secrets/heapster.cert
        - -tls_key=/secrets/heapster.key
        - -tls_client_ca=/secrets/heapster.client-ca
        - -v=9
        - -stderrthreshold=9
        volumeMounts:
          - name: heapster-secrets
            mountPath: "/secrets"
      serviceAccount: heapster
      volumes:
      - name: heapster-secrets
        secret:
          secretName: heapster-secrets
```
